//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageContent
    {
        public int Id { get; set; }
        public Nullable<int> Fk_ImageId { get; set; }
        public string DiscountText { get; set; }
        public string OfferText { get; set; }
        public string ImageContent1 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
