//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Image()
        {
            this.ImageContents = new HashSet<ImageContent>();
        }
    
        public int ImageId { get; set; }
        public Nullable<long> Length { get; set; }
        public string Name { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsImageContainsFace { get; set; }
        public Nullable<bool> IsImageContainsText { get; set; }
        public Nullable<int> RedPercentage { get; set; }
        public Nullable<int> GreenPercentage { get; set; }
        public Nullable<int> BluePercentage { get; set; }
        public Nullable<int> FaceCount { get; set; }
        public string Checksum { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageContent> ImageContents { get; set; }
    }
}
