//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public Nullable<int> Length { get; set; }
        public string Name { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsImageContainsFace { get; set; }
        public Nullable<bool> IsImageContainsText { get; set; }
        public Nullable<int> RedPercentage { get; set; }
        public Nullable<int> GreenPercentage { get; set; }
        public Nullable<int> BluePercentage { get; set; }
        public Nullable<int> FaceCount { get; set; }
        public string Checksum { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
